### ISSUE TITLE
[개발] Header layout 개발하기

### ISSUE THREAD

**Issue by kkwongs** [pigs-pango-team/pango-web#11]
**[개발] Header layout 개발하기**

1. 말씀하신 것처럼 `header.vue`파일을 `defalut.vue`파일과 분리하여 개발하겠습니다.

2. 제플린에 있는 Styleguide(Spacing)을 참고하여 `style.css`파일을 약간 수정하겠습니다.

**Comment by hjjae2** [comment]
알람이 안와 늦게나마 확인했습니다.
