### ISSUE TITLE
[개발] Content layout, AdBox component 개발하기

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/pango-web#12]
**[개발] Content layout, AdBox component 개발하기**

1. 구두로 논의한 것처럼 content.vue 콘텐츠 영역개발하겠습니다.

2. AdvertisingBox Component 개발해보겠습니다.  (광고가 표시될 AdBox 파일 작성: components/AdBox.vue, #10 )<BR>
- #10 에서 작업하려 했으나, 기본 토대만 가져오고 새롭게 작업하는 것이 꼬이지 않을 것 같아 분리하여 작업하겠습니다.
- AdvertisingBox -> AdBox로 변경해봤습니다. (의견은 편하게 주세용)

<BR>

이번 이슈(브랜치)에서 Content Layout 과 AdBox 모두 작업하여 올리도록 하겠습니다. (ContentLayout에 AdBox 노출)

<BR>

> 참고
Link1. Grid 시스템 이해하기 - https://chansbro.github.io/vue/vuetify_tutorial1
Link2. Margin by breakpoints - https://getbootstrap.com/docs/4.0/utilities/spacing/ Ex) `ma-md-2`

**Comment by hjjae2** [comment]
(이슈 먼저 확인 받고 작업했어야 했는데) 당일 이슈올리고 개발진행하게 되어 미리 확인받지 못한 점 죄송합니당.

**Comment by kkwongs** [comment]
확인했습니다!
