### ISSUE TITLE
[개발] Default.vue ESLint 오류 개선(콤마), 사이드 NavBar 제거 

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/pango-web#19]
**[개발] Default.vue ESLint 오류 개선(콤마), 사이드 NavBar 제거** 

1. Meger하는 도중에 아주 사소한 충돌 발생하여 바로 해결하여 Merge했습니다. 이 충돌은 굳이 작업자에게 묻지 않아도 해결할 수 있는 부분이라 바로 수정하여 반영했습니다. (https://github.com/pigs-pango-team/pango-web/pull/15/commits/b985e964001a908725203ca033bd0c8294eea9bd)
콤마 하나가 빠져서 현재 develop 브랜치에서 ESLint 에러 발생 합니다. (Autofix로 정상 작동 가능합니다.)
콤마 빠진 부분 수정하여 반영하겠습니다.

2. 사이드의 Navigation Bar가 존재하고 있는데, 이 부분 제거하려고 합니다. 

확인 부탁드립니다!

**Comment by kkwongs** [comment]
확인했습니다!
