### ISSUE TITLE
[개발] Footer layout 개발하기 (with common-css)

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/pango-web#7]
**[개발] Footer layout 개발하기 (with common-css)**

사전에 논의된 것 처럼 디자인 작업 끝나고 Footer 개발하려고 합니다.

```
// ~/layouts/default.vue

<v-footer :fixed="fixed" app>
      <span>&copy; {{ new Date().getFullYear() }}</span>
</v-footer>
```

1. default.vue 안에 바로 개발하기 보다 `~/layouts/footer.vue` 와 같이 파일 분리하여 만들려고 하는데 괜찮을까요?

2. 개발하면서 연관된 css 부분도 같이 작성할 수 있을 것 같습니다. 둘 다 편한대로 작성하고 merge할 때 충돌시키는 것도 괜찮을 것 같은데 어떻게 생각하시나요?

**Comment by kkwongs** [comment]
1. 완전 좋은 생각같습니다. 파일을 분리하게 되면 default.vue가 훨씬 깔끔해질 것 같습니다.

2. 각자 css를 작성하고 merge에서 충돌하면 어떻게 하는 건가요? common.css를 만들어서 작성하는 건가요?

**Comment by hjjae2** [comment]
1. 넵, 알겠습니다.

2. 각자 자유롭게 '이건 공통 css로 만들어야겠다' 라는게 있으면  common.css 와 같은 파일하나 만들어 거기에 작성한다. 물론 작성하지 않아도 된다. 만약 둘다 작성하면 merge할 때 충돌 발생한다. 충돌이 발생하면 두 사람의 코드를 보고 논의하며 정리하고 머지한다.

의 흐름인 것 같습니다. (파일명이 다르면 충돌 안나고 머지될텐데, 이때에도 동일하게 한 파일은 삭제하고 한파일에 정리하면 될 것입니다.)

개발 전에 css 누가 만들지, 어떻게 만들지 에 대해 논의해도 좋지만 또 논의하는데 시간이 쓰이고 논의보다 실제로 개발하면서 부딪히는거는 어떤지 해서 이렇게 제안해봤습니다.

**Comment by kkwongs** [comment]
잘 이해했습니다. 굳!

**Comment by hjjae2** [comment]
> *참고 (for css)* 
https://vuetifyjs.com/ko/customization/sass-variables/ 
https://vuetifyjs.com/ko/styles/spacing/
